export const PRESENCE_INTERVAL_MS = 250;
export const SAVE_POSITION_INTERVAL_MS = 30_000;
export const PRESENCE_MOVE_THRESHOLD_PX = 2;
export const PRESENCE_STATIONARY_HEARTBEAT_MS = 2_000;

export const PLAYER_MOVE_SPEED = 120;
export const PLAYER_SPRINT_MULTIPLIER = 1.5;
export const PLAYER_ANIM_SPEED = 0.12;
export const NPC_INTERACT_RADIUS_PX = 48;

export const REMOTE_INTERP_DELAY_MS = 300;
export const REMOTE_INTERP_MAX_SNAPSHOTS = 6;
export const REMOTE_SNAP_DISTANCE_PX = 96;
